version: '3.1'
services:
    #Laravel Service
    web:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      image: laravelapp
      container_name: web
      ports:
        - 8080:80
      volumes:
        - ./:/var/www/html
    #MongoDB Service
    mongo:
      image: mongo:3.6.3
      restart: always
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root
        SERVICE_TAGS: dev
        SERVICE_NAME: mongo
      container_name: mongo





