version: '3.6'
services:

  #PHP Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: digitalocean.com/php
    container_name: app
    restart: unless-stopped
    tty: true
    environment:
      SERVICE_NAME: app
      SERVICE_TAGS: dev
    volumes:
      - ./:/var/www
      - ./php/local.ini:/usr/local/etc/php/conf.d/local.ini
    working_dir: /var/www
    networks:
      - app-network

  #Nginx Service
  webserver:
    image: nginx:alpine
    container_name: webserver
    restart: unless-stopped
    tty: true
    ports:
      - "8087:80"
      - "443:443"
    volumes:
      - ./:/var/www
      - ./nginx/conf.d/:/etc/nginx/conf.d/
    networks:
      - app-network

  #Mongo Service
  mongo:
    image: mongo:3.6
    volumes:
      - mongo_data_db:/data/db
      - mongo_data_configdb:/data/configdb
    ports:
      - 27018:27017
  grandnode:
    image: grandnode/grandnode:4.10
    ports:
      - 8080:8080
    depends_on:
      - mongo

#Docker Networks
networks:
  app-network:
    driver: bridge
#Volumes
volumes:
  dbdata:
    driver: local
  mongo_data_db:
    external: true
  mongo_data_configdb:
    external: true