version: '3'
services:
    #Laravel Service
    app:
      build:
        context: .
        dockerfile: .docker/Dockerfile
      image: laravelapp
      container_name: app
      ports:
        - 8080:80
      volumes:
        - ./:/var/www/html
    #MongoDB Service
    mongodb:
      image: mongo:latest
      restart: always
      container_name: mongodb
      ports:
        - "27018:27017"
      environment:
        MONGO_INITDB_ROOT_USERNAME: root
        MONGO_INITDB_ROOT_PASSWORD: root




